### ISSUE TITLE
Schedule - APP CRASH: App dies after tapping Add to Calendar

### ISSUE THREAD

**Issue by eegraf** [challfry/TheKraken#5] opened 2020-01-25 22:10 UTC
If user accepts App Calendar access after initially denying it, the app crashes when user tries to add to Calendar. 

Steps:
Sign in first time (logged in or not)
Schedule>Any Event>Add To Calendar> DECLINE Calendar access
Exit app>Settings General>Kraken>Allow Calendar access
Return to app
Schedule>Any Event>Add To Calendar>CRASH

https://drive.google.com/file/d/1xMeQg-zaGI0rWSrs3z7RCItlEO8gJZn2/view?usp=sharing

**Comment by challfry** [comment] 2020-01-27 08:15
I think this was being caused by a bug in CollectionView updating. Should be fixed now.

**Closed** 2020-01-27 08:36 UTC
